### ISSUE TITLE
Code re-org: model training

### ISSUE THREAD

**Issue by delucchi-cmu** [lincc-frameworks/deepdisc#18]
Create a module under /src/deepdisc/model for model training.

This should handle generating training data examples, train/test/eval splits, and implement detectron trainers.

**Comment by grantmerz** [comment]
Generate training data examples should be moved to /src/deepdisc/preprocessing to keep separate from model training.  Same with training/test/eval splits.  The current training scripts assume this has been done already, and I would consider it a part of preprocessing

**Comment by grantmerz** [comment]
In order to run the training scripts, a "trainer" object needs to be created and then trained with .train().  The pieces that go into a trainer are a model, a "loader", an "optimizer" and the configs needed for both.  These can all be built in separate scripts

**Comment by grantmerz** [comment]
Code has been refactored.  This issue will be complete once the redshift network heads are added under /src/deepdisc/model/models/.  I will wait to do that until Issue #33 is completed

**Comment by grantmerz** [comment]
Actually I went ahead and placed the redshift estimation network in /src/deepdisc/models/.
