### ISSUE TITLE
Make use of `Param` objects and migrate some hardcoded values to input parameters

### ISSUE THREAD

**Issue by drewoldag** [lincc-frameworks/deepdisc#75]
Primarily this addresses the comment here to use Param objects in the deepdisc stages. https://github.com/LSSTDESC/rail_deepdisc/pull/15#discussion_r1416647180

Also want to change a couple hardcoded variables into parameters:
https://github.com/LSSTDESC/rail_deepdisc/pull/15#discussion_r1416645213
https://github.com/LSSTDESC/rail_deepdisc/pull/15#discussion_r1416644019
https://github.com/LSSTDESC/rail_deepdisc/pull/15#discussion_r1416650549

**Comment by OliviaLynn** [comment]
Closing as completed
